import prisma from '../../lib/database';
import { getAiProvider } from '../aiProvider';
import { normalizeKeyword } from '../keywordResearch/normalization';

export interface ContentPlanRequest {
  websiteId: string;
  numberOfArticles?: number;
}

export async function generateContentPlan({ websiteId, numberOfArticles = 5 }: ContentPlanRequest) {
  const website = await prisma.website.findUnique({
    where: { id: websiteId },
    include: {
      keywords: { where: { status: 'ACTIVE' }, orderBy: { opportunityScore: 'desc' }, take: 50 },
      competitors: true
    }
  });

  if (!website) {
    throw new Error('Website not found');
  }

  // Get existing articles to avoid duplicates
  const existingArticles = await prisma.article.findMany({
    where: { websiteId },
    select: { primaryKeyword: true, topic: true }
  });

  const existingNormalizedKeywords = new Set(
    existingArticles
      .map(a => a.primaryKeyword ? normalizeKeyword(a.primaryKeyword) : '')
      .filter(Boolean)
  );

  const availableKeywords = website.keywords.filter(k => 
    !existingNormalizedKeywords.has(normalizeKeyword(k.keyword))
  );

  const prompt = `
You are an expert SEO Content Strategist. Your task is to create a content plan for a website.

Website: ${website.name} (${website.url})
Industry: ${website.industry || 'General'}
Target Audience: ${website.targetAudience || 'General'}
SEO Goals: ${website.seoGoals.join(', ') || 'Increase organic traffic'}

Available Keyword Opportunities:
${availableKeywords.slice(0, 20).map(k => `- ${k.keyword} (Vol: ${k.searchVolume || 'Unknown'}, KD: ${k.difficulty || 'Unknown'}, Intent: ${k.intent || 'Unknown'})`).join('\n')}

Generate exactly ${numberOfArticles} high-quality article ideas that fill content gaps and target these keywords.
Do NOT duplicate existing content topics. 

Return your response strictly as a JSON array of objects with the following schema:
[
  {
    "topic": "Article Title/Topic",
    "targetKeyword": "The exact target keyword",
    "searchIntent": "INFORMATIONAL, COMMERCIAL, or TRANSACTIONAL",
    "wordCount": 1500
  }
]
`;

  const provider = getAiProvider();
  const completion = await provider.generateCompletion({
    userPrompt: prompt,
    temperature: 0.7,
    maxTokens: 2000,
    systemPrompt: "You are a professional SEO content planner. Only return valid JSON matching the exact schema."
  });

  let parsedPlan;
  try {
    const jsonMatch = completion.match(/\[[\s\S]*\]/);
    parsedPlan = JSON.parse(jsonMatch ? jsonMatch[0] : completion);
  } catch (e) {
    console.error('Failed to parse AI content plan output:', completion);
    throw new Error('AI returned invalid structured data.');
  }

  if (!Array.isArray(parsedPlan)) {
    throw new Error('AI did not return an array');
  }

  const createdArticles = [];
  let dayOffset = 1;

  for (const item of parsedPlan) {
    if (!item.targetKeyword || !item.topic) continue;

    const normKeyword = normalizeKeyword(item.targetKeyword);
    if (existingNormalizedKeywords.has(normKeyword)) {
      continue; // Skip duplicates generated by AI
    }

    const scheduledDate = new Date();
    scheduledDate.setDate(scheduledDate.getDate() + dayOffset);
    dayOffset++;

    const article = await prisma.article.create({
      data: {
        websiteId,
        topic: item.topic,
        title: item.topic,
        primaryKeyword: item.targetKeyword,
        wordCount: item.wordCount || 1500,
        status: 'PLANNED',
        scheduledAt: scheduledDate,
      }
    });

    createdArticles.push(article);
    existingNormalizedKeywords.add(normKeyword); // prevent duplicates within same batch
  }

  return createdArticles;
}
